#!/bin/bash
#
# comp (Shell Script)
#
# Objetivo: Compilar e adicionar programas escritos em linguagem C
# ao pacote de processamento sísmico MADAGASCAR.
# 
# IMPORTANTE: Depende do pacote MADAGASCAR instalado para funcionar!
#
#	      -MADAGASCAR é um pacote open source de processamento sísmico (http://www.ahay.org/wiki/Main_Page)
# 
# Site: http://www.dirackslouge.online
#
# Versão 2.0
#
# Programador: Rodolfo A. C. Neves 10/01/2019 (original 1.0)
#	       Rodolfo A. C. Neves 11/05/2019 (modificada 2.0)
# 
# email (manutenção): rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Verificar se a variável RSFSRC está setada
[ -z "$RSFSRC" ] && {
	echo -e "\033[31m$(basename $0): AVISO: A variável RSFSRC não está setada!\033[m" 	
	echo -e "\033[31m$(basename $0): AVISO: Informe onde está instalada a sua cópia local do pacote Madagascar!\033[m" 
	read -p "RSFSRC: " RSFSRC
}

#----------------{ Configuração de variáveis }-----------------------------#

# Diretório principal da sua instalação do pacote MADAGASCAR
PASTA_PRINCIPAL_MADAGASCAR="$RSFSRC"

# Seu diretório de usuário dentro do pacote MADAGASCAR
PASTA_USUARIO_MADAGASCAR="$RSFSRC/user"
 
# Versão deste programa
VERSAO="Versão 1.0"

OPCAO="$1"
PASTA_USUARIO_FORNECIDA="$2"

NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Compila e adiciona programas escritos em linguagem C ao pacote de processamento sísmico MADAGASCAR."
PARAMETROS="-h --help::Exibe esta mensagem de ajuda e sai
-v --version::Exibe a Versão do programa e sai
-c pastaDeUsuario::Compila programas de uma pasta de usuário específica do pacote MADAGASCAR"
EXEMPLO_DE_USO="~$ $(basename $0) -c pastaDeUsuario"

#--------------------------------------------------------------------------#

# Verificar se o usuário forneceu algum parâmetro ao programa
[ -z "$OPCAO" ] && {
	echo -e "\033[31m$(basename $0): ERRO(1): O usuário não forneceu nenhum parâmetro!\033[m" 
	echo -e "\033[31mDigite $(basename $0) -h para obter ajuda!\033[m" 	
	exit 1 
}


case "$OPCAO" in
-h | --help) ## Exibir ajuda
	clear
	exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
	exit 0
;;

-v | --version) ## Exibir versão deste programa
	echo -e "\033[00;01m$VERSAO\033[m"
	exit 0
;;

-c) ## Compilar e adicionar programas ao MADAGASCAR

	# Foi fornecida uma pasta de usuário a este programa?
	# Sim, troque o nome em $PASTA_USUARIO_MADAGASCAR
	# Não, utilize a pasta $PASTA_USUARIO_MADAGASCAR como foi definida
	if [ -n "$PASTA_USUARIO_FORNECIDA" ] 
	then

		PASTA_USUARIO_FORNECIDA="$PASTA_PRINCIPAL_MADAGASCAR/user/$PASTA_USUARIO_FORNECIDA"

		# Verificar se a pasta fornecida é um diretório de 
		# usuário presente na instalação MADAGASCAR
		if [ ! -d "$PASTA_USUARIO_FORNECIDA" ]
		then
			echo -e "\033[31m$(basename $0): ERRO(2): Pasta de usuário $PASTA_USUARIO_FORNECIDA NÃO encontrada!\033[m"
			exit 2
		fi

		PASTA_USUARIO_MADAGASCAR="$PASTA_PRINCIPAL_MADAGASCAR/user/$2"

	else

		echo -e "\033[31m$(basename $0): ERRO(3): Nenhuma pasta de usuário foi fornecida a este programa!\033[m"
		echo -e "\033[31mDigite $(basename $0) -h para obter ajuda\033[m"
		exit 3

	fi

	echo -e "\033[35mcompilando $PASTA_USUARIO_MADAGASCAR ...\033[m"

	# Mover para a pasta de usuário e rodar o scons
	if cd "$PASTA_USUARIO_MADAGASCAR" && scons
	then
		# Informar o usuário se ocorrer erro de compilação
		echo -e "\033[35mCompilação realizada com sucesso!\033[m"

		# Mover para o diretório principal do MADAGASCAR
		cd "$PASTA_PRINCIPAL_MADAGASCAR"

		# Adicione o programa ao pacote MADAGASCAR
		if sudo scons install
		then
			echo -e "\033[35mInstalação realizada com sucesso!\033[m"
		else
			echo -e "\033[31m$(basename $0): ERRO(5): Erro durante a instalação!\033[m"
			exit 5
		fi	

	else
		echo "\033[31m$(basename $0): ERRO(2): Erro de compilação em $PASTA_USUARIO_MADAGASCAR\033[m"
		exit 2
	fi

	exit 0
;;

*) ## Usuário forneceu parâmetro desconhecido ao programa
	echo -e "\033[31m$(basename $0): ERRO(3): Opção $OPCAO desconhecida!\033[m"
	echo -e "\033[31mDigite $(basename $0) -h para obter ajuda\033[m"
	exit 3
;;
esac
