#!/bin/bash
#
# getscons (Shell Script)
#
# Depende do programa lynx para funcionar. Utilize 'sudo apt-get install lynx' para instalar.
#
# Objetivo: Baixar arquivos SConstruct da página do MADAGASCAR para a pasta atual
# no formato correto do SConstruct.
# 
# IMPORTANTE: MADAGASCAR é um pacote open source de processamento sísmico. 
# Disponível em (http://www.ahay.org/wiki/Main_Page)
# 
# Site: http://www.dirackslouge.online
#
# Versão 1.1
#
# Programador: Rodolfo A. C. Neves 30/06/2019
# 
# Email (Manutenção): rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

#----------------{ Configuração de variáveis }-----------------------------#

# Versão deste programa
VERSAO="Versão 1.1"

# Opção passada pelo usuário
OPCAO="$1"

NOME_PROGRAMA="$(basename $0)" 
DESCRICAO="Baixar arquivos SConstruct da página do MADAGASCAR para a pasta atual"
PARAMETROS="-h --help::Exibe esta mensagem de ajuda e sai
-v --version::Exibe a Versão do programa e sai
-l <link>::Baixa o SConstruct da página <link> para a pasta atual
"
EXEMPLO_DE_USO="~$ $(basename $0) -l <link> # Baixa o SConstruct do <link> para a pasta atual
"
#--------------------------------------------------------------------------#


# Verificar se o usuário forneceu algum parâmetro
[ -z "$OPCAO" ] && {
	MENSAGEMERRO="O usuário não forneceu nenhum parâmetro!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
}

case "$OPCAO" in
-h | --help) ## Exibir ajuda
	clear
	exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
	exit 0
;;

-v | --version) ## Exibir versão
	echo -e "\033[00;01m$VERSAO\033[m"
	exit 0
;;

-l)

	LINK="$2"

	# Verificar se o usuário passou um link como parâmetro
	[ -z "$LINK" ] && {
		MENSAGEMERRO="O usuário não forneceu nenhum link!\nDigite $(basename $0) -h para obter ajuda!"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "$MENSAGEMERRO"
	}

	TMP="./tmp.txt"

	FILE="./SConstruct"

	# Se já tiver um SConstruct na pasta, perguntar ao usuário se deseja sobreescrever
	[ -f "$FILE" ] && {

		read -p "Já há um SConstruct na pasta atual, deseja sobreescrever? (s/n)" RESPOSTA

		if [ "$RESPOSTA" == "s" ]
		then

			rm "$FILE"

		elif [ "$RESPOSTA" == "n" ] 
		then

			echo "SConstruct da pasta atual mantido"
			echo "Programa encerrado"
			exit 0

		else

			MENSAGEMERRO="Opção $RESPOSTA desconhecida!\nPrograma encerrado"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"

		fi

	}

	LINK=$(echo "$LINK" | cut -d"," -f1)

	## Cabeçalho para o SConstruct
	HEAD="SConstruct (§)\n\nObjetivo:\n\nVersão\n\nSite:\n\nProgramador: $(date +%d/%m/%Y)\n\nEmail:\n\nLicença:"

	echo -e "$HEAD" | sed 's/^/# /' | sed 's/§/Python/' >> "$FILE"

	lynx -dump -dont_wrap_pre -nolist "$LINK" | sed '/End()/q'>> "$FILE"

	sed -i '/up \[pdf\]/d' "$FILE"
	
	exit 0
	
;;

*) ## Usuário forneceu parâmetro desconhecido
	MENSAGEMERRO="Opção $OPCAO desconhecida!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "3" "$MENSAGEMERRO"
;;
esac
