#!/bin/bash
# 
# Jonas (Shell Script)
# 
# Objetivo: Criar atalhos para pastas e aliases permanentes.
# Os aliases ficarão armazenados em um arquivo $HOME/.aliases.sh
# Adicione a linha abaixo ao seu arquivo $HOME/.bashrc
#
# source $HOME/.aliases.sh
# 
# Site: http://www.dirackslounge.online
# 
# Versão 1.1
# 
# Programador: Rodolfo A. C. Neves (Dirack)	 27/12/2018
# 
# email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

# Versão atual do programa
VERSAO="Versão 1.1"

# Verificar se o arquivo de aliases está referenciado
# no arquivo $HOME/.bashrc, se não estiver referencie
grep -x -q 'source $HOME/.aliases.sh #Arquivo de aliases definidos pelo programa jonas NÃO EDITAR!' ~/.bashrc
[ "$?" -ne "0" ] && {
	echo 'source $HOME/.aliases.sh #Arquivo de aliases definidos pelo programa jonas NÃO EDITAR!' >> $HOME/.bashrc
}

# Verificar se o usuário passou parâmetros para o programa
if [ -z "$1" ]
then
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
fi

NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Criar atalhos para pastas e aliases permanentes. Os aliases ficarão armazenados em um arquivo \$HOME/.aliases.sh Adicione a linha abaixo ao seu arquivo $HOME/.bashrc source $HOME/.aliases.sh"
PARAMETROS="-h --help::Exibe este menu e sai 
-v --version::Exibe a versão do programa e sai 
-a ::Gera atalho para a pasta atual (alias)
-c ::Gera comando personalizado (alias)
-l --list::Exibe a lista de aliases já cadastrados"
EXEMPLO_DE_USO="~$"

case "$1" in

	-h | --help)

		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
		;;

	-v | --version)
		
		echo "$VERSAO"
		exit 0
		;;

	-a)

		# Peça para o usuário dar nome ao atalho
		echo -e "Criando atalho para a pasta\n $PWD\n"
		read -p "Dê nome ao atalho: " nome

		# Verificar se algum nome foi passado ao atalho
		[ -z "$nome" ] && {
			MENSAGEMERRO="Usuário não deu nenhum nome ao atalho!"			
			exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "$MENSAGEMERRO"
		}
	 
		# Guarda a localização atual, substitua os espaços por '\ '
		atalho=$(pwd | sed 's/ /\\ /g')

		## escreva o atalho criado no arquivo .aliases.sh
		sudo echo alias $nome=\"cd $atalho\" >> $HOME/.aliases.sh
		source $HOME/.bashrc # Validar o atalho		
		echo  "Atalho criado com sucesso!"
		exit 0
		;;
	-c)
		##gerar comando personalizado
		read -p "Digite o apelido (alias) do comando: " apelido

		# Verificar se algum apelido foi passado ao atalho
		[ -z "$apelido" ] && {
			MENSAGEMERRO="Usuário não deu nenhum apelido ao atalho!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "3" "$MENSAGEMERRO"
		}

		# Verificar se o alias já existe
		 lista=$(cut -d" " -f2 $HOME/.aliases.sh | cut -d "=" -f1 | grep -x "$apelido") 

		[ -n "$lista" ] && {
			MENSAGEMERRO="O alias $apelido já está cadastrado!"	
			exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"
		}

		read -p "Digite o comando: " comando

		# Verificar se algum comando foi passado pelo usuário		
		[ -z "$comando" ] && {
			MENSAGEMERRO="Usuário não passou nenhum comando!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "5" "$MENSAGEMERRO"
		}
		
		##escreva o comando no arquivo .aliases.sh
		sudo echo alias $apelido=\"$comando\" >> $HOME/.aliases.sh
		source $HOME/.bashrc # Validar atalho 
		exit 0
		;;

	-l | --list ) ## Exibir a lista de aliases já cadastrados

		 cut -d" " -f2 $HOME/.aliases.sh | cut -d "=" -f1 
	;;

	*)
		MENSAGEMERRO="Opção $1 desconhecida!\nDigite $0 -h para obter ajuda."
		exibirMensagemErroProgramaFormatada "$(basename $0)" "6" "$MENSAGEMERRO"
	;;
esac
