#!/bin/bash
# 
# Lembrete (Shell Script)
# 
# Objetivo: Armazenar lembretes e idéias no arquivo $HOME/.post
# 
# Site: http://www.dirackslounge.online
# 
# Versão 1.3.0
# 
# Programador: Rodolfo A. C. Neves (Dirack)	 27/12/2018
# 
# email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

VERSAO="Shellinclude - 1.3.0"
SEPARADOR=":"
ARQUIVO_LEMBRETES="$HOME/.post"

# Verificar se o usuário passou algum parâmetro pela linha de comandos
[ -z "$1" ] && {
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
}

# Verificar se o arquivo de banco de dados exite
# Se não, crie
[ -f "$ARQUIVO_LEMBRETES" ] || {
	touch "$ARQUIVO_LEMBRETES"
}

NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Armazenar lembretes e idéias no arquivo $ARQUIVO_LEMBRETES"
PARAMETROS="-h --help::Exibe esta mensagem de ajuda e sai
-v --version::Exibe a versão do programa e sai
-a --add::Adicionar lembretes
-l --list::Listar lembretes
-r --remove::Remover lembretes"
EXEMPLO_DE_USO="~$ $0 -a tag -m \"Mensagem\" # Adicionar lembrete tag=Mensagem
	~$ $0 -l tag # Procurar por lembrete chamado 'tag'
"

case "$1" in
	-h | --help) # Exibir ajuda
		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
	;;

	-v | --version) # Exibir versão do programa
		echo "$VERSAO"
		exit 0	
	;;

	-a | --add) # Adicionar lembretes, a sintaxe é: ./lembrete -a tag -m "Mensagem"

		# Verificar se o usuário forneceu corretamente o comando
		[ -z "$2" -o -z "$3" -o "$3" != "-m" -o -z "$4" ] && {

			MENSAGEMERRO="Sintaxe incorreta do comando!\nA sintaxe correta é:\n$0 -a tag -m Mensagem"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "$MENSAGEMERRO"
		}
		
		# Verificar se lembrete já existe
		existe=$(cut -d"${SEPARADOR}" -f1 $ARQUIVO_LEMBRETES | grep -x "$2")
		[ -z "$existe" ] || {

			MENSAGEMERRO="Lembrete já cadastrado!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "3" "$MENSAGEMERRO"
		}
		
		# Campos do arquivo $HOME/.post
		# tag:lembrete:data:hora
		# Usa uma máscara '§' para o caractere ':'
		MSG="$4"
		MSG=$(echo "$MSG" | sed 's/:/§/g')
		echo "$2${SEPARADOR}$MSG${SEPARADOR}$(date +%d-%m-%Y)${SEPARADOR}$(date +%H-%M-%S)" >> "$ARQUIVO_LEMBRETES"
		
		echo "lembrete cadastrado com sucesso!"
		exit 0
	;;

	-l | --list) # Listar lembretes armazenados no arquivo $HOME/.post
	    
		# Se nenhuma chave específica for passada, mostre todos
		[ -z "$2" ] && {
			echo "Lembretes cadastrados: "
			cut -d"${SEPARADOR}" -f1 "$ARQUIVO_LEMBRETES"

			echo -e "\n*Digite $0 -l NomeDoLembrete para exibir um lembrete específico."
			exit 0
		}

		# Se uma chave específica for passada, procure o lembrete e a linha
		existe=$(cut -d"${SEPARADOR}" -f1 $ARQUIVO_LEMBRETES | grep -nx "$2" | cut -d":" -f1)

		# Se o lembrete NÃO foi encontrado, informe ao usuário
		if [ -z "$existe" ] 
		then 
			MENSAGEMERRO="Lembrete NÃO encontrado!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"
		else

		# Se o lembrete foi encontrado, exiba o lembrete ao usuário
			TMP=$(sed -n "${existe}p" $ARQUIVO_LEMBRETES)
			LEMBRETE=$(echo "$TMP" | cut -d"${SEPARADOR}" -f1)
			DATA=$(echo "$TMP" | cut -d"${SEPARADOR}" -f3 | tr '-' '/')
			HORA=$(echo "$TMP" | cut -d"${SEPARADOR}" -f4 | tr '-' ':')
			MSG=$(echo "$TMP" | cut -d"${SEPARADOR}" -f2 | sed 's/§/:/g')
			echo "LEMBRETE= $LEMBRETE"
			echo "DATA= $DATA"
			echo "HORA= $HORA"
			echo "MENSAGEM= $MSG"
			exit 0
		fi

		
	;;

	-r | --remove) # remover lembrete armazenado no arquivo $HOME/.post

		# Verificar se o usuário forneceu corretamente o comando
		[ -z "$2" ] && {

			MENSAGEMERRO="Sintaxe incorreta do comando!\nA sintaxe correta é:\n$0 -a tag -m Mensagem"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "5" "$MENSAGEMERRO"
		}

		# Verificar se lembrete já existe
		existe=$(cut -d"$SEPARADOR" -f1 $ARQUIVO_LEMBRETES | grep -nx "$2" | cut -d":" -f1)

		if [ -z "$existe" ] 
		then
			MENSAGEMERRO="Lembrete NÃO encontrado!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "6" "$MENSAGEMERRO"
		else
			sed -i "${existe}d" $ARQUIVO_LEMBRETES		
			echo "lembrete $2 apagado!"
			exit 0
		fi

		
	;;

	*)

		MENSAGEMERRO="Opção $1 desconhecida!\nDigite $0 para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "7" "$MENSAGEMERRO"
	;;
esac
