#!/bin/bash
#
# madagainstall (Shell Script)
# 
# Objetivo: Script de instalação do pacote de processamento sísmico Madagascar.
# 
# Site: https://dirack.github.io
# 
# Versão 1.2
# 
# Programador:  Murilo Santiago (Original-1.0) 23/03/2020
#
# Programador:	Rodolfo A C Neves (Dirack) (Atualização-1.2) 24/03/2020
#		-Incorporação à biblioteca Shellinclude
#
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

## Verificar se o usuário forneceu $1 e $2
if [ -z "$1" ]
then
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
fi

# Versão deste programa
VERSAO="Shellinclude - Versão 1.2"

## Variáveis que armazenam mensagem de ajuda do programa
NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Script de instalação do pacote de processamento sísmico Madagascar."
PARAMETROS="-h --help::Exibe essa tela de ajuda e sai
-v --version::Exibe a versão do programa e sai
-i --install::Instalar o Madagascar na pasta $HOME"
EXEMPLO_DE_USO="~$ $(basename $0) -i # Instalar o Madagascar"

case "$1" in
	-h | --help) ## Exibe a ajuda
		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
	;;

	-v | --version) ## Exibe a versão do programa
		echo $VERSAO
		exit 0
	;;

	-i | --install) ## Instalar o pacote Madagascar na pasta atual
		
		URL="https://ufpr.dl.sourceforge.net/project/rsf/madagascar/madagascar-3.0/madagascar-3.0.1.tar.gz"
		echo -e "\nBaixando o pacote madagascar do servidor ${URL}...\n"
                if [ -f "$HOME/madagascar-3.0.1.tar.gz" ]
                then
                        echo -e "...Já existe uma versão do pacote Madagascar em $HOME\n"
                else
                        wget -c "$URL" -P ${HOME} &>/dev/null
                fi

                echo -e "Descompactando a versão 3.0 do pacote Madagascar...\n"
		if [ "-d" "$HOME/madagascar-3.0" ]
		then
			echo -e "...Já existe uma versão descompactada do pacote Madagascar em $HOME\n"
		else
			if tar -xzvf "$HOME/madagascar-3.0.1.tar.gz" -C "$HOME" &>/dev/null
			then
				cd ${HOME}/madagascar-3.0
			else

				MENSAGEMERRO="Ocorreu um erro inesperado ao descompactar o pacote em $HOME/madagascar-3.0"
				exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "$MENSAGEMERRO"
			fi
		fi

		# Instalar dependências
		DEPENDENCIAS="libxaw7-dev freeglut3-dev libnetpbm10-dev libgd-dev libplplot-dev libavcodec-dev libcairo2-dev libjpeg-dev swig python-dev python-numpy g++ gfortran libopenmpi-dev libfftw3-dev libsuitesparse-dev python-epydoc scons git emacs25"

		echo -e "Instalar dependências...\n"
		for i in $DEPENDENCIAS
		do
			echo "...Instalando $i"
			sudo apt-get install -y "$i" 1>/dev/null
		done
		
		# Configuração do madagascar
		echo -e "Configurar o Madagascar para instalacao...\n"
		./configure --prefix=$HOME/madagascar

		# Instalação do pacote Madagascar	
		echo -e "Instalar o pacote Madagascar...\n"
		if sudo make install
		then
			# Definição das variáveis de ambiente do Madagascar no .bashrc
			export DATAPATH=$HOME/rsfdata/
			source "$HOME/madagascar/share/madagascar/etc/env.sh"

			# Verificar se as variáveis de ambiente já estão setadas corretamente
			grep -xq "source $HOME/madagascar/share/madagascar/etc/env.sh" "$HOME/.bashrc"
			[ "$?" -ne "0" ] && {
				echo "source $HOME/madagascar/share/madagascar/etc/env.sh" >> "$HOME/.bashrc"
			}

			grep -xq "export DATAPATH=$HOME/rsfdata/" "$HOME/.bashrc"
			[ "$?" -ne "0" ] && {
				echo "export DATAPATH=$HOME/rsfdata/" >> "$HOME/.bashrc"
			}

			source "$HOME/.bashrc"
			echo "Testando a instalação..."
			if sfspike n1=100 k1=30 | sfdisfil
			then
				echo -e "...Instalação finalizada com sucesso! :)\n"
				echo -e "Para utilizar o Madagascar neste terminal carregue as variáveis de ambiente com:\nsource $HOME/.bashrc\nOu abra um novo terminal..."
			else
				MENSAGEMERRO="Ocorreu um erro inesperado durante a instalação do pacote Madagascar!"
				exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"

			fi
		else
			MENSAGEMERRO="Ocorreu um erro inesperado durante a instalação do pacote Madagascar!"
			exibirMensagemErroProgramaFormatada "$(basename $0)" "5" "$MENSAGEMERRO"
		fi
	;;

	*)
		MENSAGEMERRO="Opção $1 Desconhecida!\nDigite $(basename $0) -h para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "6" "$MENSAGEMERRO"
esac
