#!/bin/bash
#
# madagainstall (Shell Script)
# 
# Objetivo: Script de instalação do pacote de processamento sísmico Madagascar.
# 
# Site: https://dirack.github.io
# 
# Versão 1.2
# 
# Programador:  Murilo Santiago (Original-1.0) 23/03/2020
#
# Programador:	Rodolfo A C Neves (Dirack) (Atualização-1.2) 24/03/2020
#		-Incorporação à biblioteca Shellinclude
#
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

## Verificar se o usuário forneceu $1 e $2
if [ -z "$1" ]
then
	MENSAGEMERRO="Usuário não ofereceu parâmetros ao programa!\nDigite $(basename $0) -h para obter ajuda!"
	exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "$MENSAGEMERRO"
fi

# Versão deste programa
VERSAO="Shellinclude - Versão 1.2"

## Variáveis que armazenam mensagem de ajuda do programa
NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Script de instalação do pacote de processamento sísmico Madagascar."
PARAMETROS="-h --help::Exibe essa tela de ajuda e sai
-v --version::Exibe a versão do programa e sai
-i --install::Instalar o Madagascar na pasta atual"
EXEMPLO_DE_USO="~$ $(basename $0) -i # Instalação do Madagascar na pasta atual"

case "$1" in
	-h | --help) ## Exibe a ajuda
		clear
		exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
		exit 0
	;;

	-v | --version) ## Exibe a versão do programa
		echo $VERSAO
		exit 0
	;;

	-i | --install) ## Instalar o pacote Madagascar na pasta atual
		
		URL="https://ufpr.dl.sourceforge.net/project/rsf/madagascar/madagascar-3.0/madagascar-3.0.1.tar.gz"
		echo "Baixando o pacote madagascar do servidor ${URL}..."
		wget -c "$URL" > ${HOME}

		tar -xzvf "~/madagascar-3.0.1.tar.gz"

		cd ${HOME}/madagascar-3.0

		# Instalar dependências
		DEPENDENCIAS="libxaw7-dev freeglut3-dev libnetpbm10-dev libgd-dev libplplot-dev libavcodec-dev libcairo2-dev libjpeg-dev swig python-dev python-numpy g++ gfortran libopenmpi-dev libfftw3-dev libsuitesparse-dev python-epydoc scons git emacs25"

		echo "Instalar dependências..."
		for i in $DEPENDENCIAS
		do
			sudo apt-get install "$i"
		done
		
		# Configuração do madagascar
		echo "	Configurar o Madagascar para instalacao..."
		./configure --prefix=$HOME/madagascar

		# Instalação do pacote Madagascar	
		echo "Instalar o pacote Madagascar..."
		sudo make install
	
		# Definição das variáveis de ambiente do Madagascar no .bashrc
		export DATAPATH=$HOME/rsfdata/
		echo "source $HOME/madagascar/share/madagascar/etc/env.sh" >> .bashrc
		echo "export DATAPATH=$HOME/rsfdata/" >> .bashrc
	;;

	*)
		MENSAGEMERRO="Opção $1 Desconhecida!\nDigite $(basename $0) -h para obter ajuda"
		exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "$MENSAGEMERRO"
esac
