#!/bin/bash
#
# suite (Shell Script)
#
# Objetivo: Testar programas desenvolvidos em linguagem C para o
# pacote de processamento sísmico MADAGASCAR. Este programa move uma
# cópia do código fonte a ser testado para uma pasta de testes dentro da pasta user, 
# na instalação do pacote madagascar, compila o código
# e adiciona o programa ao pacote madagascar para ser testado.
# 
# IMPORTANTE: Depende do programa 'comp' e do MADAGASCAR instalado para funcionar!
#
#	      -comp é um programa da pasta da biblioteca Shell Script (https://github.com/Dirack/Shell-Script)		
#
#	      -MADAGASCAR é um pacote open source de processamento sísmico (http://www.ahay.org/wiki/Main_Page)
#
# Site: http://www.dirackslouge.online
#
# Versão 1.0
#
# Programador: Rodolfo A. C. Neves 11/05/2019
#
# email (Manutenção): rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

# Biblioteca de funções para formatar a mensagem de ajuda
source mensagemAjuda.sh 

# Biblioteca de funções para formatar a mensagem de erro
source mensagemErro.sh

#----------------{ Configuração de variáveis }-----------------------------#

# Diretório principal da sua instalação do pacote MADAGASCAR
PASTA_PRINCIPAL_MADAGASCAR="$HOME/Downloads/madagascar-2.0-1/madagascar-2.0"

# Pasta PADRÃO do usuário de testes dentro do pacote MADAGASCAR
PASTA_TESTES_MADAGASCAR="$PASTA_PRINCIPAL_MADAGASCAR/user/testes"
 
# Versão deste programa
VERSAO="Versão 1.0"

NOME_PROGRAMA="$(basename $0)"
DESCRICAO="Testador de programas desenvolvidos em linguagem C para o pacote de processamento sísmico MADAGASCAR. Este programa move uma cópia do código fonte escolhido para a pasta de testes no pacote MADAGASCAR. Compila o código e adiciona o programa ao pacote MADAGASCAR para ser testado."
PARAMETROS="-h --help::Exibe esta mensagem de ajuda e sai
-v --version::Exibe a Versão do programa e sai
-c nomeDoPrograma::Compilar e instalar o programa no pacote MADAGASCAR
-c nomeDoPrograma -sv::Compilar, instalar e 'scons view' na pasta atual"
EXEMPLO_DE_USO="~$ $(basename $0) -c teste.c

	~$ $(basename $0) -c teste.c -sv
"

#--------------------------------------------------------------------------#

OPCAO="$1"
NOME_PROGRAMA_TESTADO="$2"
SCONS_VIEW_PASTA_ATUAL="$3"

case "$OPCAO" in
-h | --help) ## Exibir ajuda
	clear
	exibirMensagemAjudaProgramaFormatada "$NOME_PROGRAMA" "$DESCRICAO" "$PARAMETROS" "$EXEMPLO_DE_USO"
	exit 0
;;

-v | --version) ## Exibir versão
	echo -e "\033[00;01m$VERSAO\033[m"
	exit 0
;;

-c) ## Compilar e adicionar programa ao MADAGASCAR
	
	if [ -z "$NOME_PROGRAMA_TESTADO" ] 
	then

		exibirMensagemErroProgramaFormatada "$(basename $0)" "1" "Um nome de programa deve ser fornecido!"
	else

		## Verificar se o programa existe no endereço fornecido
		if [ ! -f "$NOME_PROGRAMA_TESTADO" ] 
		then
			exibirMensagemErroProgramaFormatada "$(basename $0)" "2" "Programa $NOME_PROGRAMA_TESTADO não encontrado!"
		fi

		## Verificar o formato do nome do programa
		echo "$NOME_PROGRAMA_TESTADO" | grep -qs "^M*" # Começa com M maiúsculo ?
		echo "$NOME_PROGRAMA_TESTADO" | grep -qs ".*\.c" # Tem a extensão '.c' ?

		if [ "$?" -ne "0" ] 
		then

			exibirMensagemErroProgramaFormatada "$(basename $0)" "3" "Os nomes dos programas devem seguir o padrão 'Mnome.c', primeira letra M maiúsculo e a extensão .c"

		fi
		
		## Copiar o programa para a pasta de testes
		cp "$NOME_PROGRAMA_TESTADO" "$PASTA_TESTES_MADAGASCAR"

		## Formatar o nome do programa para o SConstruct
		NOME_PROGRAMA_TESTADO_FORMATADO=$(echo "$NOME_PROGRAMA_TESTADO" | cut -d"M" -f2 | cut -d"." -f1)

		## Adicionar o nome do programa ao SConstruct
		sed -i "6s/^.*$/$NOME_PROGRAMA_TESTADO_FORMATADO/" "$PASTA_TESTES_MADAGASCAR/SConstruct"

		## Fazer a compilação do arquivo na pasta testes
		if comp -c testes
		then

			## Realizar um 'scons view' na pasta atual
			[ "$SCONS_VIEW_PASTA_ATUAL" == '-sv' ] && {
				scons view
			}

		fi

	fi


	exit 0
;;

*) ## Usuário forneceu uma opção desconhecida
	exibirMensagemErroProgramaFormatada "$(basename $0)" "4" "Opção $OPCAO desconhecida!\nDigite $(basename $0) -h para obter ajuda"
;;
esac
