#!/bin/bash
#
# suite (Shell Script)
#
# Objetivo: Suíte de testes de programas para o
# pacote de processamento sísmico MADAGASCAR.
# 
# IMPORTANTE: Depende do programa comp para funcionar!
#
# Site: http://www.dirackslouge.online
#
# Versão 1.0
#
# Programador: Rodolfo A. C. Neves 11/05/2019
#
# email: rodolfo_profissional@hotmail.com
# 
# Licença: Software de uso livre e código aberto.

#----------------{ Configuração de variáveis }-----------------------------#
#	Ao mudar o endereço da pasta na variável USER, o programa pode 
#	ser adaptado para a compilação de programas de outro usuário.

# Diretório principal do pacote MADAGASCAR
TOP="/home/dirack/Downloads/madagascar-2.0-1/madagascar-2.0"

# Pasta PADRÃO do usuário de testes dentro do pacote MADAGASCAR
USER="$TOP/user/testes"
 
# Versão deste programa
VERSAO="Versão 1.0"

#--------------------------------------------------------------------------#

MENSAGEM_USO="
$(basename $0) [-h | -v | -c ]
-h --help Exibe esta mensagem de ajuda e sai
-v --version Exibe a Versão do programa e sai
-c nomeDoPrograma Realiza a compilação e teste do programa no pacote MADAGASCAR

Exemplo de uso: 
	bash$ $0 -c teste.c
"

case "$1" in
-h | --help) ## Exibir ajuda
	echo -e "$MENSAGEM_USO"
	exit 0
;;

-v | --version) ## Exibir versão
	echo "$VERSAO"
	exit 0
;;

-c) ## Compilar e adicionar programas ao MADAGASCAR
	
	## $2 é o nome do programa a ser testado
	## Se não for fornecido $2, avise o usuário e encerre
	if [ -z "$2" ] 
	then

		echo -e "\033[31mERRO: Nome do programa a ser testado não foi fornecido!\033[m"
		exit 1
	else

		## Verificar se o programa existe no endereço fornecido
		if [ ! -f "$2" ] 
		then
			echo -e "Programa \033[31m$2\033[m não encontrado!"
			exit 2 
		fi

		## Verificar o formato do nome do programa
		echo "$2" | grep -qs "^M*" # Começa com M maiúsculo ?
		echo "$2" | grep -qs ".*\.c" # Tem a extensão '.c' ?

		if [ "$?" -ne "0" ] 
		then

			echo $?
			echo -e "\033[031mERRO: Os nomes dos programas do MADAGASCAR devem seguir o padrão\033[m"
			echo -e "\033[34mM\033[mnome\033[34m.c\033[m"			
			echo -e "\033[31ma primeira letra M maiúsculo\033[m"
			echo -e "\033[31ma extensão .c\033[m"

			exit 3

		fi
		
		## Copiar o programa para a pasta de testes
		cp "$2" "$USER"

		## Formatar o nome do programa para o SConstruct
		NOME=$(echo "$2" | cut -d"M" -f2 | cut -d"." -f1)

		## Adicionar o nome do programa ao SConstruct
		sed -i "6s/^.*$/$NOME/" "$USER/SConstruct"

		## Fazer a compilação
		if comp -c testes
		then

			[ "$3" == '-sv' ] && {
				scons view
			}

		fi

	fi


	exit 0
;;

*) ## Usuário forneceu parâmetro desconhecido
	echo -e "\033[31mERRO: Opção $1 desconhecida!\033[m"
	echo "\033[31mDigite $0 -h para obter ajuda\033[m"
	exit 3
;;
esac
