.TH LIPSUM 1 "07 ABR 2020" "Versão 1.0" "LIPSUM Manual de uso"

.SH NOME
lipsum - Gerar texto aleatório na tela do terminal com um número de linhas definido pelo usuário.

.SH RESUMO
.B lipsum
[\-h] [\-\-help] [-v] [\-\-version] [\-r] [\-\-random]

.SH DESCRIÇÃO
.PP
LIPSUM é um auxiliar para geração de dummy text, muito útil no desenvolvimento web, quando
o programador pretende textar várias formatações de texto e estilo das páginas HTML.

.SH OPÇÕES
LIPSUM aceita as seguintes opções:
.TP 8
.B  \-h, \-\-help
Exibe a mensagem de ajuda do programa e sai.
.TP 8
.B \-v, \-\-version
Exibe a versão do programa.
.TP 8
.B \-r \-\-random <n linhas>
Gera um texto na tela do terminal com n linhas. 

.SH EXEMPLOS DE USO
.PP
Gerar uma linha de texto aleatório (padrão):

	~$ lipsum -r
.PP
Gerar 10 linhas de texto aleatório:

	~$ lipsum -r 10

.SH AMBIENTE
LIPSUM armazena uma página com texto aleatório (dummy text) em um diretório '.lipsum' gerado
automaticamente na pasta onde o programa está instalado. O programa precisa de conexão com a 
internet para baixar uma página de template com texto aleatório do site da lipsum 
em 'https://br.lipsum.com/' e armazenar no diretório '.lipsum'.

.SH FILES
LIPSUM é instalado na pasta /shellinclude, e precisa de permissão de execução.
Outros usuários podem preferir instalar o programa no seu diretório de preferência, o que
não afetará a sua usabilidade, desde que este diretório esteja definido na sua $PATH.

.SH SUGESTÕES E 'BUG REPORTS'
Qualquer bug encontrado deve ser reportado para o repositório do
Github da Biblioteca Shell Script na aba 'issues' em:

	https://github.com/Dirack/Shellinclude/issues

E deve-se notificar por email o responsável pela manutenção do código:

	rodolfo_profissional@hotmail.com (Rodolfo Dirack).

Quando reportar um bug é importante explicitar em que situação este foi produzido
para que possa ser reproduzido pelo autor, a versão do programa e toda informação
relevante será bem vinda.

.SH AUTORES
Rodolfo A. C. Neves (Dirack), e o Grupo de Programação Aplicada à Geofísica (GPGEOF).

Contato:

-Página no github (Dirack) https://github.com/Dirack

-Página no github (GPGEOF) https://github.com/gpgeof.

.SH VEJA TAMBÉM
Visite o nosso canal de divulgação científica no Youtube (Geofisicando) em:

	https://www.youtube.com/channel/UCi5XD5PCQtPrIRD0H_GJvag

Site oficial do MADAGASCAR:

	http://www.ahay.org/wiki/Main_Page
