.TH MORSE 1 "24 FEV 2020" "Versão 1.3.0" "MORSE Manual de uso"

.SH NOME
morse - Enviar email pelo terminal. 

.SH RESUMO
.B morse
[\-h] [\-\-help] [-v] [\-\-version] [\-e]

.SH DESCRIÇÃO
.PP
MORSE é uma interface para o programa 'sendemail'. Este auxilia no envio de emails pelo terminal.

.SH OPÇÕES
MORSE aceita as seguintes opções:
.TP 8
.B  \-h, \-\-help
Exibe a mensagem de ajuda do programa e sai.
.TP 8
.B \-v, \-\-version
Exibe a versão do programa e sai.
.TP 8
.B \-e
Abre o prompt para receber as informações do email pela linha de comandos.

.SH EXEMPLOS DE USO
.PP
Enviar email pelo terminal.

	~$ morse -e

.SH AMBIENTE
MORSE utiliza o programa sendemail para enviar o email pelo terminal
e o vim como editor de texto padrão para escrita das mensagens.

.SH FILES
MORSE é instalado na pasta /shellinclude, e precisa de permissão de execução.
Outros usuários podem preferir instalar o programa no seu diretório de preferência, o que
não afetará a sua usabilidade, desde que este diretório esteja na sua $PATH.

.SH SUGESTÕES E 'BUG REPORTS'
Qualquer bug encontrado deve ser reportado para o repositório do
Github da Biblioteca Shell Script na aba 'issues' em:

	https://github.com/Dirack/Shellinclude/issues

E deve-se notificar por email o responsável pela manutenção do código:

	rodolfo_profissional@hotmail.com (Rodolfo Dirack).

Quando reportar um bug é importante explicitar em que situação este foi produzido
para que possa ser reproduzido pelo autor, a versão do programa e toda informação
relevante será bem vinda.

.SH AUTORES
Rodolfo A. C. Neves (Dirack), e o Grupo de Programação Aplicada à Geofísica (GPGEOF).

Contato:

-Página no github (Dirack) https://github.com/Dirack

-Página no github (GPGEOF) https://github.com/gpgeof.

.SH VEJA TAMBÉM
Visite o nosso canal de divulgação científica no Youtube (Geofisicando) em:

	https://www.youtube.com/channel/UCi5XD5PCQtPrIRD0H_GJvag

