
SRC = §main§
CC = §compilador§
DEP = $(SRC:§extensao§=§extensaoObjeto§)
MAIN = $(SRC:§extensao§=§extensaoBinario§)

all:	$(DEP) run

run:	$(MAIN)
	§run§

%§extensaoObjeto§:	%§extensao§
	§compilacaoObjeto§

%§extensaoBinario§:	%§extensao§
	§compilacaoBinario§

clean:	
	rm $(DEP)
	rm $(MAIN)
